### ISSUE TITLE
Add policy pack - Tagging Helpers for Cost_Center

### ISSUE THREAD

**Issue by vkumbha** [turbot/guardrails-samples#865]
**Control objective**
Example of the cost center tags, i imagine a regex that would look for anything matching `*cost*center*` in a case insensitive way and the setting the tag key to Cost_Center

- [x] AWS - https://github.com/turbot/guardrails-samples/pull/867
- [x] Azure - https://github.com/turbot/guardrails-samples/pull/868
- [x] GCP - https://github.com/turbot/guardrails-samples/pull/869
   (Note: GCP Labels does not allow capital letters. So, the tag key would be `cost_center`
   >   Invalid field "user_labels_list"; key "Cost_Center" does not conform to regular expression
   >   "[\p{Ll}\p{Lo}][\p{Ll}\p{Lo}\p{N}_-]{0,62}"; first character "C" is not a non-uppercased letter (Unicode character
   >   class Ll or Lo)

**Remediation**
The remediation action(s) to satisfy the control objective.

**Categories**
Proposed primary category and categories from the [available list of categories](https://github.com/turbot/guardrails-samples/tree/main/policy_packs#readmemd).

**Additional context**

**Comment by dboeke** [comment]
@vkumbha the regex should match any key with the pattern `*cost*center*` case insensitive and replace with `Cost_Center`
